

services:
  migration:
    image: aravindaravind123/social-media-publisher-backend:latest
    command: sh -c "sleep 10 && alembic upgrade head"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    image: aravindaravind123/social-media-publisher-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
      - migration

  worker:
    image: aravindaravind123/social-media-publisher-worker:latest
    command: celery -A app.celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - backend

  redis:
    image: redis:7

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre123
      POSTGRES_DB: social_publisher_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    image: aravindaravind123/social-media-publisher-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend
  
volumes:
  postgres_data: