"""Add celery_task_id to Post table

Revision ID: 558e55fe375d
Revises: 5cac75b3d8c6
Create Date: 2026-02-26 14:57:10.345062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558e55fe375d'
down_revision: Union[str, Sequence[str], None] = '5cac75b3d8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('celery_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'celery_task_id')
    # ### end Alembic commands ###
